name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'backend.Dockerfile'
      - 'backend.dockerignore'
      - 'docker-compose.yml'
      - 'nginx.conf'
      - 'setup-vm.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Log deployment info
            echo "Deploying to $(hostname)"
            echo "Current user: $(whoami)"
            echo "Current directory: $(pwd)"
            
            # Check if deployment directory exists
            if [ ! -d "~/apps/deployment" ]; then
              echo "Error: Deployment directory not found. Please run setup-vm.sh first."
              exit 1
            fi
            
            # Check if backend directory exists
            if [ ! -d "~/apps/video-summary/backend" ]; then
              echo "Error: Backend directory not found. Please run setup-vm.sh first."
              exit 1
            fi
            
            # Create backup of current backend
            BACKUP_DIR="~/apps/video-summary/backend_backup_$(date +%Y%m%d_%H%M%S)"
            echo "Creating backup in $BACKUP_DIR"
            cp -r ~/apps/video-summary/backend "$BACKUP_DIR"
            
            # Update deployment repository
            cd ~/apps/deployment
            git pull
            
            # Update backend repository
            cd ~/apps/video-summary/backend
            if ! git pull; then
              echo "Error: Failed to update backend repository"
              exit 1
            fi
            
            # Deploy using docker compose
            cd ~/apps/deployment
            echo "Deploying backend..."
            if ! docker compose -f docker-compose.yml up -d --build backend nginx; then
              echo "Error: Failed to deploy backend"
              echo "Restoring from backup..."
              rm -rf ~/apps/video-summary/backend
              mv "$BACKUP_DIR" ~/apps/video-summary/backend
              docker compose -f docker-compose.yml up -d --build backend nginx
              exit 1
            fi
            
            # Verify backend is running
            echo "Verifying backend..."
            if ! docker compose -f docker-compose.yml ps | grep -q "backend.*Up"; then
              echo "Error: Backend failed to start"
              exit 1
            fi
            
            # Health check
            echo "Running health check..."
            if ! curl -f http://localhost:5050/health; then
              echo "Error: Backend health check failed"
              exit 1
            fi
            
            echo "✅ Backend deployment completed successfully" 