name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/deploy-backend.yml'
      - 'backend.Dockerfile'
      - 'backend.dockerignore'
      - 'docker-compose.yml'
      - 'nginx.conf'
      - 'apps.yaml'
      - 'setup-vm.sh'
      - 'manage-apps.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update deployment repository
            cd /home/ubuntu/apps/deployment
            git pull
            
            # Get backend path from apps.yaml
            BACKEND_PATH=$(yq e '.groups.video-summary.base_path' apps.yaml)/backend
            
            # Update backend repository
            cd $BACKEND_PATH
            git pull
            
            # Deploy using docker compose
            cd /home/ubuntu/apps/deployment
            docker compose -f docker-compose.yml up -d --build backend nginx 